### ISSUE TITLE
Issue when trying to use dot product in RSL with aqsis

### ISSUE THREAD

**Issue by jateen19** [aqsis/aqsis#24]
I am trying to run my surface shader using aqsis and RSL and am facing this warning when I try to use dot product. 
WARNING: Unresolved function dot will be treated as a DSO at runtime. 
I have deleted and reinstalled aqsis both on windows and WSL and still facing the same issue. Is there something that I'm doing wrong?

**Comment by pgregory** [comment]
I'm presuming you managed to resolve this yourself?
