### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by mapulse** [aqsis/aqsis#4]
CMake Error at CMakeLists.txt:9 (message):
  Aqsis requires an out of source build.  Please clean any cmake-generated
  files from the source directory, create a separate build directory and run
  'cmake path_to_source [options]' there.

-- Configuring incomplete, errors occurred!
See also "/home/lynx/aqsis/CMakeFiles/CMakeOutput.log".

how can I fix that error?

**Comment by pgregory** [comment]
The best way is to follow these steps..

1. Create a 'project' folder.
  * `mkdir aqsis`
2. cd into that folder and clone the project there 
  * `git clone git@github.com:aqsis/aqsis.git`
3. Create a build directory within the project directory.
  * `mkdir build`
4. cd into the build directory and run cmake.
  * `cd build`
  * `cmake ../aqsis`

**Comment by Hibou57** [comment]
The build directory can also be inside the source directory. From `aqsis/build`, it is just `cmake ..` instead of  `cmake ../aqsis`. It is useful for the cases where having the build directory beside the source directory, is not possible.
